export enum Virtue {
  WISDOM = 'Wisdom',
  COURAGE = 'Courage',
  HUMANITY = 'Humanity',
  JUSTICE = 'Justice',
  TEMPERANCE = 'Temperance',
  TRANSCENDENCE = 'Transcendence',
}

export interface Strength {
  id: number;
  name: string;
  virtue: Virtue;
  description: string;
}

export interface FamilyMember {
  name: string;
  pronouns: string;
}

export interface UserProfile {
  name: string;
  gender: string;
  pronouns: string;
  occupation: string;
  pets: FamilyMember[];
  partner?: FamilyMember;
  children: FamilyMember[];
  topStrengths: number[]; // IDs of strengths
  isOnboarded: boolean;
}

export interface Activity {
  id: string;
  strengthId: number;
  title: string;
  description: string;
  completedAt?: number; // Timestamp
  journalEntry?: string;
  isCustom?: boolean; // If generated by AI specifically for mood
  isManualLog?: boolean; // If manually logged by user from Garden
}

export interface DailyState {
  date: string; // ISO date string YYYY-MM-DD
  activities: Activity[];
  hasShuffled: boolean;
}

export interface StrengthProgress {
  strengthId: number;
  level: number;
  exp: number; // Experience points
}

export type ViewState = 'onboarding' | 'dashboard' | 'guide' | 'history' | 'settings';

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  suggestedActivities?: Activity[];
}